#!/usr/bin/env bash
# Build a production Zirconium kernel and bootable ISO without starting QEMU.
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

BUILD_MODE="release"
SELFTEST="false"
MAKE_ISO="true"
CLEAN_STAGE="false"
OUTPUT_ISO="$SCRIPT_DIR/kernel.iso"
ZIG_BIN="${ZIG:-zig}"

usage() {
    cat <<'EOF'
Usage: ./build_iso.sh [options]

Build the kernel and create a bootable ISO.  No disk image is created and
QEMU is not started.

Options:
  --debug             Build Debug instead of ReleaseFast (not for real-hardware boot)
  --release           Build ReleaseFast (default)
  --selftest          Enable the embedded ring-3 boot self-test
  --no-selftest       Disable the embedded self-test (default)
  --no-iso            Build zig-out/bin/kernel, but do not create kernel.iso
  --output FILE       Write the ISO to FILE (default: ./kernel.iso)
  --clean             Remove the previous ISO/staging directory before building
  -h, --help          Show this help

Environment:
  ZIG=/path/to/zig     Use a specific Zig executable (must be Zig 0.16.x)
EOF
}

while (($# > 0)); do
    case "$1" in
        --debug)
            BUILD_MODE="debug"
            shift
            ;;
        --release)
            BUILD_MODE="release"
            shift
            ;;
        --selftest)
            SELFTEST="true"
            shift
            ;;
        --no-selftest)
            SELFTEST="false"
            shift
            ;;
        --no-iso)
            MAKE_ISO="false"
            shift
            ;;
        --output)
            (($# >= 2)) || { echo "error: --output requires a path" >&2; exit 2; }
            OUTPUT_ISO="$2"
            shift 2
            ;;
        --clean)
            CLEAN_STAGE="true"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "error: unknown option: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ "$OUTPUT_ISO" != /* ]]; then
    OUTPUT_ISO="$SCRIPT_DIR/$OUTPUT_ISO"
fi

command -v "$ZIG_BIN" >/dev/null 2>&1 || {
    echo "error: Zig executable not found: $ZIG_BIN" >&2
    exit 1
}

ZIG_VERSION="$($ZIG_BIN version)"
if [[ ! "$ZIG_VERSION" =~ ^0\.16\.(.+)$ ]]; then
    echo "error: Zig 0.16.x is required; found $ZIG_VERSION" >&2
    echo "       Set ZIG=/path/to/zig if the correct compiler is not in PATH." >&2
    exit 1
fi

if [[ "$MAKE_ISO" == "true" ]] && ! command -v grub-mkrescue >/dev/null 2>&1; then
    echo "error: grub-mkrescue is required to create the ISO" >&2
    echo "       Use --no-iso to build only zig-out/bin/kernel." >&2
    exit 1
fi

STAGE_DIR="$SCRIPT_DIR/build/iso-stage"
MANIFEST="$SCRIPT_DIR/build/kernel-build.env"

if [[ "$CLEAN_STAGE" == "true" ]]; then
    rm -rf "$STAGE_DIR"
    rm -f "$OUTPUT_ISO"
fi

if [[ "$BUILD_MODE" == "release" ]]; then
    BUILD_ARGS=(-Drelease -Dselftest="$SELFTEST")
    OPTIMIZE_NAME="ReleaseFast"
else
    BUILD_ARGS=(-Doptimize=Debug -Dselftest="$SELFTEST")
    OPTIMIZE_NAME="Debug"
fi

printf '=== Zirconium kernel build ===\n'
printf 'Zig:       %s (%s)\n' "$ZIG_BIN" "$ZIG_VERSION"
printf 'Mode:      %s\n' "$OPTIMIZE_NAME"
printf 'Selftest:  %s\n' "$SELFTEST"
printf 'ISO:       %s\n\n' "$OUTPUT_ISO"

printf '=== Building kernel ===\n'
"$ZIG_BIN" build "${BUILD_ARGS[@]}"

KERNEL_BIN="$SCRIPT_DIR/zig-out/bin/kernel"
[[ -f "$KERNEL_BIN" ]] || {
    echo "error: expected kernel was not produced: $KERNEL_BIN" >&2
    exit 1
}

mkdir -p "$SCRIPT_DIR/build"
GIT_REV="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"
KERNEL_SIZE="$(stat -c '%s' "$KERNEL_BIN" 2>/dev/null || wc -c < "$KERNEL_BIN")"
cat > "$MANIFEST" <<EOF
# Generated by build_iso.sh; do not edit by hand.
ZIG_VERSION=$ZIG_VERSION
OPTIMIZE=$OPTIMIZE_NAME
SELFTEST=$SELFTEST
GIT_REV=$GIT_REV
KERNEL_BIN=$KERNEL_BIN
KERNEL_SIZE=$KERNEL_SIZE
EOF

if [[ "$MAKE_ISO" == "true" ]]; then
    printf '\n=== Preparing GRUB ISO tree ===\n'
    rm -rf "$STAGE_DIR"
    mkdir -p "$STAGE_DIR/boot/grub"
    install -m 0644 "$KERNEL_BIN" "$STAGE_DIR/boot/kernel.bin"
    install -m 0644 "$SCRIPT_DIR/grub.cfg" "$STAGE_DIR/boot/grub/grub.cfg"

    printf '=== Creating ISO ===\n'
    mkdir -p "$(dirname -- "$OUTPUT_ISO")"
    rm -f "$OUTPUT_ISO"
    grub-mkrescue -o "$OUTPUT_ISO" "$STAGE_DIR"
    [[ -f "$OUTPUT_ISO" ]] || {
        echo "error: grub-mkrescue did not produce: $OUTPUT_ISO" >&2
        exit 1
    }
    ISO_SIZE="$(stat -c '%s' "$OUTPUT_ISO" 2>/dev/null || wc -c < "$OUTPUT_ISO")"
    printf 'ISO_SIZE=%s\n' "$ISO_SIZE" >> "$MANIFEST"
fi

printf '\n=== Build complete ===\n'
printf 'Kernel: %s (%s bytes)\n' "$KERNEL_BIN" "$KERNEL_SIZE"
printf 'Manifest: %s\n' "$MANIFEST"
if [[ "$MAKE_ISO" == "true" ]]; then
    printf 'ISO: %s (%s bytes)\n' "$OUTPUT_ISO" "$(stat -c '%s' "$OUTPUT_ISO" 2>/dev/null || wc -c < "$OUTPUT_ISO")"
    printf '\nFlash/write this ISO to the boot medium; this script does not run QEMU.\n'
else
    printf 'ISO creation was disabled (--no-iso).\n'
fi
